{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1004195948&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbcefc40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=101011628&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd0a1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1220781484497428481&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd0a640>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1262633137324077057&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd0aa90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=13329732&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbce0d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=20790118&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd0a850>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=25669608&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd0a910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=2703181339&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd0aee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=29488350&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd12370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=3310061541&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd127c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=33417701&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd12c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=3365084051&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd1b0a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=480496989&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd1b4f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=64165042&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd1b940>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=743395104740651008&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd1bd60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=782780281468121089&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd1b7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=883858851933691904&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd1b250>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=889915185934237699&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd12b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=907479550279471104&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd12a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=911372935&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd125b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=938125693&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd122e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=963790885937995777&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd0acd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=9719042&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77fbd0aa90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
