{'cap': {'english': 0.3912159239072283, 'universal': 0.40673978557586005}, 'display_scores': {'english': {'astroturf': 1.3, 'fake_follower': 0.1, 'financial': 0.0, 'other': 0.1, 'overall': 0.4, 'self_declared': 0.0, 'spammer': 0.0}, 'universal': {'astroturf': 1.2, 'fake_follower': 0.4, 'financial': 0.0, 'other': 0.4, 'overall': 0.4, 'self_declared': 0.0, 'spammer': 0.0}}, 'raw_scores': {'english': {'astroturf': 0.26, 'fake_follower': 0.02, 'financial': 0.0, 'other': 0.02, 'overall': 0.07, 'self_declared': 0.01, 'spammer': 0.0}, 'universal': {'astroturf': 0.25, 'fake_follower': 0.07, 'financial': 0.0, 'other': 0.09, 'overall': 0.07, 'self_declared': 0.0, 'spammer': 0.0}}, 'user': {'majority_lang': 'en', 'user_data': {'id_str': '1117212855684747264', 'screen_name': 'PoliticsAreBad'}}}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1175047638&include_rts=True&count=200 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f378fd906d0>, 'Connection to api.twitter.com timed out. (connect timeout=60)'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1253073159789727746&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f378f3d8a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=15115280&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f378f3d8310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=16931008&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f378f3d8ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=193055087&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f378f1df1f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=21651982&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f378f1df640>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=23103413&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f378fd6dbe0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=25073877&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f378f1ff970>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=356875264&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f378f1ff4f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=36726336&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f378f3ed4f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=39508427&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f378f1df070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=44925425&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f378f3d8ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=63504638&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f378f3d8310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=921468286453321728&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f378fd90730>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=945014509701423105&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f378fd90280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
